import json
d = {}
d["pdf_test_51.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"36/2025/QĐ-UBND","ngay_ban_hanh":"20/06/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Ban hành Quy chế quản lý kiến trúc thị trấn Đạ M'ri, huyện Đạ Huoai, tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_52.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"06/10/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_53.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"12/12/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_54.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"27/06/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_55.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"16/12/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_56.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"16/12/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_57.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"08/07/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_58.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"77/2025/QĐ-UBND","ngay_ban_hanh":"27/10/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN THÀNH PHỐ HẢI PHÒNG","trich_yeu":"","nguoi_ky":""}
d["pdf_test_59.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"29/07/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN THÀNH PHỐ HẢI PHÒNG","trich_yeu":"","nguoi_ky":""}
d["pdf_test_60.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"08/07/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_61.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"90/2025/QĐ-UBND","ngay_ban_hanh":"01/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Kiểm soát bệnh tật tỉnh Ninh Bình trực thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_62.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"91/2025/QĐ-UBND","ngay_ban_hanh":"01/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Điều dưỡng Người có công Ninh Bình trực thuộc Sở Nội vụ tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_63.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"92/2025/QĐ-UBND","ngay_ban_hanh":"01/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Kiểm nghiệm Dược phẩm, mỹ phẩm tỉnh Ninh Bình trực thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_64.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"94/2025/QĐ-UBND","ngay_ban_hanh":"05/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Nuôi dưỡng thương bệnh binh nặng và Điều dưỡng Người có công Hà Nam thuộc Sở Nội vụ tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_65.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"50/2025/QĐ-UBND","ngay_ban_hanh":"25/06/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH BẾN TRE","trich_yeu":"Sửa đổi, bổ sung một số điều của Quy định ban hành kèm theo Quyết định số 44/2024/QĐ-UBND ngày 23/10/2024 của UBND tỉnh ban hành Quy định về bồi thường, hỗ trợ, tái định cư khi Nhà nước thu hồi đất trên địa bàn tỉnh Bến Tre","nguoi_ky":""}
d["pdf_test_66.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"63/2025/QĐ-CTUBND","ngay_ban_hanh":"17/10/2025","co_quan_ban_hanh":"CHỦ TỊCH ỦY BAN NHÂN DÂN TỈNH PHÚ THỌ","trich_yeu":"Ban hành Quy chế phối hợp trong quản lý người nước ngoài cư trú, hoạt động trên địa bàn tỉnh Phú Thọ","nguoi_ky":"Trần Duy Đông"}
d["pdf_test_67.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"07/2025/QĐ-UBND","ngay_ban_hanh":"28/04/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Quy định khung giá dịch vụ quản lý vận hành nhà chung cư trên địa bàn tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_68.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"06/2025/QĐ-UBND","ngay_ban_hanh":"28/04/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Quy định khung giá thuê nhà ở xã hội được đầu tư xây dựng không bằng vốn đầu tư công, nguồn tài chính công đoàn trên địa bàn tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_69.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"05/2025/QĐ-UBND","ngay_ban_hanh":"28/04/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Quy định phân cấp thẩm quyền sát hạch, cấp chứng chỉ hành nghề hoạt động xây dựng hạng I, cấp chứng chỉ năng lực hoạt động xây dựng hạng I trên địa bàn tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_70.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"30/2025/QĐ-UBND","ngay_ban_hanh":"28/05/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Quy định giá cho thuê đối với nhà ở cũ thuộc tài sản công trên địa bàn tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_71.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"39/2025/QĐ-UBND","ngay_ban_hanh":"30/06/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Ban hành Quy chế quản lý kiến trúc đô thị Thạnh Mỹ, tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_72.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"39/2025/QĐ-UBND","ngay_ban_hanh":"30/06/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Ban hành Quy chế quản lý kiến trúc đô thị Lộc Thắng, tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_73.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"40/2025/QĐ-UBND","ngay_ban_hanh":"30/06/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG","trich_yeu":"Ban hành Quy chế quản lý kiến trúc đô thị Lạc Dương, tỉnh Lâm Đồng","nguoi_ky":"Phạm Nhông Thái"}
d["pdf_test_74.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"10/06/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH BẾN TRE","trich_yeu":"","nguoi_ky":""}
d["pdf_test_75.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"10/06/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH BẾN TRE","trich_yeu":"","nguoi_ky":""}
with open(r"e:\OCR-LLM_Research\OCR-LLM_Research\data\benchmark\gt_part3.json","w",encoding="utf-8") as f:
    json.dump(d,f,ensure_ascii=False,indent=2)
print(f"Part 3: {len(d)} entries saved")
