import json
d = {}
d["pdf_test_13.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"104/2025/QĐ-UBND","ngay_ban_hanh":"10/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Ban Quản lý Khu Đại học Nam Cao và Khu Công nghệ cao tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_14.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"08/2026/QĐ-TTg","ngay_ban_hanh":"24/04/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_15.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"112/2025/QĐ-UBND","ngay_ban_hanh":"19/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Tam Điệp thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_16.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"113/2025/QĐ-UBND","ngay_ban_hanh":"19/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Thanh Liêm thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_17.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"118/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Nam Trực thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_18.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"119/2025/QĐ-UBND","ngay_ban_hanh":"29/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Bệnh viện Đa khoa Nho Quan thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_19.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"09/2026/QĐ-TTg","ngay_ban_hanh":"29/04/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_20.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"120/2025/QĐ-UBND","ngay_ban_hanh":"29/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Bệnh viện Đa khoa Kim Sơn thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_21.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"","ngay_ban_hanh":"08/08/2025","co_quan_ban_hanh":"THỦ TƯỚNG CHÍNH PHỦ","trich_yeu":"","nguoi_ky":""}
d["pdf_test_22.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"122/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Duy Tiên thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_23.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"123/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Kim Sơn thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_24.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"124/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Hải Hậu thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_25.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"125/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Giao Thủy thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_26.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"126/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Lý Nhân thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_27.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"127/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Nho Quan thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_28.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"128/2025/QĐ-UBND","ngay_ban_hanh":"26/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Y tế Vụ Bản thuộc Sở Y tế tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_29.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"137/2025/QĐ-UBND","ngay_ban_hanh":"29/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Thanh tra tỉnh Ninh Bình","nguoi_ky":"Phạm Quang Ngọc"}
d["pdf_test_30.pdf"]={"loai_van_ban":"QUYẾT ĐỊNH","so_hieu":"138/2025/QĐ-UBND","ngay_ban_hanh":"29/09/2025","co_quan_ban_hanh":"ỦY BAN NHÂN DÂN TỈNH NINH BÌNH","trich_yeu":"Ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Ban Quản lý dự án đầu tư xây dựng Hà Nam","nguoi_ky":"Phạm Quang Ngọc"}
with open(r"e:\OCR-LLM_Research\OCR-LLM_Research\data\benchmark\gt_part1.json","w",encoding="utf-8") as f:
    json.dump(d,f,ensure_ascii=False,indent=2)
print(f"Part 1: {len(d)} entries saved")
